version: "3"
services:

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    networks:
      - orchestrator-service
    ports:
      - "27017:27017"

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "9092:9092"
    networks:
      - orchestrator-service
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
    volumes:
        - ./data/kafka/data:/var/lib/kafka/data

  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - orchestrator-service
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: [ "kafka:29092" ]
    depends_on:
      - kafka

  service-um:
    build: './service-um'
    container_name: service-um
    depends_on:
      - mongodb
      - kafka
    networks:
      - orchestrator-service
    environment:
      - KAFKA_BOOTSTRAP_SERVERS= kafka:29092
      - MONGODB_URI= mongodb://mongodb:27017/orders-db
    ports:
      - "8081:8081"

  services-dois:
    build: './services-dois'
    container_name: services-dois
    depends_on:
      - mongodb
      - kafka
    networks:
      - orchestrator-service
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - MONGODB_URI= mongodb://mongodb:27017/orders-db
    ports:
      - "8084:8084"

  orchestrator-service:
    build: './orchestrator-service'
    container_name: orchestrator-service
    depends_on:
      - kafka
    networks:
      - orchestrator-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8585:8585"

networks:
  orchestrator-service:
    driver: bridge
