global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "service-um"
    metrics_path: /prometheus
    static_configs:
      - targets: ["192.168.0.102:8082"]

  - job_name: "orchestrator-service"
    metrics_path: /prometheus
    static_configs:
      - targets: ["192.168.0.102:8585"]

  - job_name: "service-dois"
    metrics_path: /prometheus
    static_configs:
      - targets: [ "192.168.0.102:8084" ]